### PR TITLE
Linting and MySQL lib update

### PR DESCRIPTION
**Pull request by mNm-server**

### CODE REVIEW

**Comment by outsider31000** [comment]
You do realize this is for vorp?

**Comment by mNm-server** [comment]
Yes?

**Comment by AndrewR3K** [comment]
Thanks for the update! Love to see contributions.

however, I am using oxmysql with all my new scripts and plan to go through and migrate all old scripts to oxmy.

**Comment by mNm-server** [comment]
Understood but Ox is depreciating the exports and already is backward compatible with the MySQL lib which is the best/most optimized use for the DB calls.

Feel free to close it but this is a working version and can be seen being used by quite a few players.

**Comment by AndrewR3K** [comment]
Awesome, I appreciate the contribution!

I will do some testing on this when I get home and am at my Computer 🤠

**Pull request merged**
